version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: app_dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
        - ./db:/var/lib/mysql
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - ./phoenix:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
